# Install NodeJS using packages crafted by nodesource.
---
- name: Ensure the system can use the HTTPS transport for APT
  stat: path=/usr/lib/apt/methods/https
  register: apt_https_transport

- name: Install HTTPS transport for apt
  apt: pkg=apt-transport-https state=installed
  when: not apt_https_transport.stat.exists

- name: Import the nodesource GPG key into apt
  apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key state=present

- name: Add nodesource deb repository
  apt_repository: repo='deb https://deb.nodesource.com/node {{ ansible_distribution_release }} main' state=present

- name: Add nodesource deb-src repository
  apt_repository: repo='deb-src https://deb.nodesource.com/node {{ ansible_distribution_release }} main' state=present

- name: Install NodeJS
  apt: pkg=nodejs state=installed update_cache=yes

- name: Install npm packages
  npm: name={{ item }} global=yes state=present
  with_items: npm_packages
  when: item != 'not_really_a_package'
